### PR TITLE
Fix #65: Adds --script-readable option for `env openshift` command

### LINKED ISSUE #65: Add --script-readable option for `env openshift` command
`vagrant service-manager env openshift` displays the openshift connection information in human-readable format.

adding `--machine-readable` to command (i.e. `vagrant service-manager env openshift --machine-readable`) should display the connection information in machine readable format.

This should help other tools which are consuming plugin to parse the output feasibly.

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #65

### CODE REVIEW

**Comment by brgnepal** [comment]
@navidshaikh @bexelbie : I am not getting the expected output on `env openshift`.

Tested Environment:

```
Host : Fedora23
Service-manager plugin : Plugin from master branch
Box : ADB release candidate 1.8.0 (https://github.com/projectatomic/adb-atomic-developer-bundle/issues/299)
Provider : Virtualbox
```

Logs - https://gist.github.com/budhrg/cc0fccd0f36cea8fcc3f

**Comment by navidshaikh** [comment]
>  I am not getting the expected output on env openshift.

@budhrg : 

The output in the gist you mentioned is the expected output. :-) 

```
➜  centos-openshift-setup git:(master) ✗ vagrant service-manager env openshift --script-readable
OPENSHIFT_URL=https://10.1.2.2:8443
OPENSHIFT_WEB_CONSOLE=https://10.1.2.2:8443/console
```

**Comment by brgnepal** [comment]
:+1:  LGTM

**Comment by LalatenduMohanty** [comment]
LGTM

**Pull request merged**
