### PR TITLE
Issue #214 Making the load of libvirt conditional and only occuring o…

### PR DESCRIPTION
**Pull request by hferentschik**
…n Linux

I found a not too intrusive way to make libvirt optional.

### CODE REVIEW

**Comment by brgnepal** [comment]
@hferentschik Please update `CHANGELOG` with your changes.

**Comment by hferentschik** [comment]
> Please update CHANGELOG with your changes.

I thought whoever merges the pull request can do it. Less potential merge conflicts. Are you otherwise ok with it? Then I can update CHANGLELOG and merge.

**Comment by brgnepal** [comment]
@hferentschik 

That's the rule we are following at the moment(which I am not in favor of) regardless of any merge conflicts we face :disappointed: .

**Comment by hferentschik** [comment]
The rule is to update the CHANGELOG, but whether this is happening as part of the pull request or the merge is not important, right? The CONTRIBUTING page mentions it as a potential step for the merger of the pull request.

**Comment by brgnepal** [comment]
> The rule is to update the CHANGELOG, but whether this is happening as part of the pull request or the merge is not important, right?

Right now it is rule to update as part of PR. 
I would like to have discussion around it if we want to change its behavior :+1:

**Comment by brgnepal** [comment]
Code looks good. Need someone who can verify it in Mac functionally.

**Comment by hferentschik** [comment]
@LalatenduMohanty do you still want to test this or are you ok to merge?

**Comment by praveenkumar** [comment]
@hferentschik look it need a rebase.

**Pull request merged**
