### PR TITLE
Updates the CHANGELOG.md

### PR DESCRIPTION
**Pull request by navidshaikh**
- Updated the CHANGELOG.md
- Moved the changelog from old repo

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Do we need the change log of adbinfo here ? May be not . As the old change log will be at https://github.com/projectatomic/vagrant-adbinfo/blob/master/CHANGELOG.md anyway for foreseeable future

**Comment by navidshaikh** [comment]
@LalatenduMohanty : I think we'll deprecate the old repo.

**Comment by LalatenduMohanty** [comment]
@navidshaikh IMO we should keep the old repo for considerable future. There is no harm in keeping the old repo. We should update the readme of the old repo saying the development has ceased and new stuff happening here.

**Comment by bexelbie** [comment]
I agree that a wholesale copy of the old change log is unnecessary.  We should have a footnote somewhere that mentions this is a successor to vagrant adbinfo, but the development path of adbinfo belongs to adbinfo. We are standing the shoulders of those giants :)

**Comment by navidshaikh** [comment]
@bexelbie @LalatenduMohanty : Updated the changelog as per comments.

**Comment by bexelbie** [comment]
2 requests: 
- please verify that all post 0.0.1 changes are in this to set us straight. 
- please say the plugin was forked and extended, not renamed. I think that is more descriptive.

**Comment by navidshaikh** [comment]
@bexelbie 

> 2 requests:
> please verify that all post 0.0.1 changes are in this to set us straight.
> please say the plugin was forked and extended, not renamed. I think that is more descriptive.

Good points, updated the PR.

**Comment by bexelbie** [comment]
LGTM

**Pull request merged**
