### PR TITLE
Fix #287: Removed Unnecessary TODO file

### LINKED ISSUE #287: Remove unnecessary TODO file from repo
Remove unnecessary `TODO` file from repo as most of the progress is tracked by milestones

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #287

### CODE REVIEW

**Comment by navidshaikh** [comment]
We should remove the file from SPEC file as well then
https://github.com/projectatomic/vagrant-service-manager/blob/master/vagrant-service-manager.spec#L89

**Comment by brgnepal** [comment]
@navidshaikh Done thanks.

**Comment by navidshaikh** [comment]
LGTM

**Comment by brgnepal** [comment]
retest this please

**Pull request merged**
