### PR TITLE
testing for pr. PLEAS EIGNORE

### PR DESCRIPTION
**Pull request by dharmit**
PLEASE IGNORE THIS PR. IT IS FOR TESTING PURPOSE ONLY

### CODE REVIEW

**Comment by dharmit** [comment]
#build

**Comment by hferentschik** [comment]
Are there any links to the build itself?

**Comment by dharmit** [comment]
@hferentschik I am not sure if you'll be able to view this. But here's the build result - https://ci.centos.org/job/vagrant-service-manager%20PR/1/console

It's very simple "Hello World"-ish test to see if a Jenkins build is triggered upon opening a PR. That worked when I opened this PR.

Hpwever, we need to modify the permissions provided in GitHub token used by CentOS CI so that it can report back with a sucesss/failure upon build completion.

**Comment by hferentschik** [comment]
>  I am not sure if you'll be able to view this. But here's the build result - https://ci.centos.org/job/vagrant-service-manager%20PR/1/console

I am, thanks. Looking forward to see some working CI integration. Maybe I can integrate my vagrant-spec test harness into this?

**Pull request closed without merging**
