### PR TITLE
Fix #429 Minor language and formatting edits to Proxy section etc.

### LINKED ISSUE #429: Make Proxy setting instructions easier to understand

### PR DESCRIPTION
**Pull request by Preeticp**
Fix for issue #429

### CODE REVIEW

**Comment by brgnepal** [comment]
LGTM :+1:

**Comment by hferentschik** [comment]
@Preeticp Could you please open an issue for this change and reference it in the commit message. Even though it is a minor change it should go through the proper process.

**Comment by Preeticp** [comment]
@hferentschik, I did this is as part of fix for ADB issue #566; https://github.com/projectatomic/adb-atomic-developer-bundle/issues/566. Can I reference the same, or do I need to create a separate issue in the vagrant service manager repository?

**Comment by hferentschik** [comment]
> or do I need to create a separate issue in the vagrant service manager repository?

Yes please. We need to have an issue in service-manager as well to properly track changes within the repo as well (plan milestones, cut changelogs, map changes/commits to issues, etc)

**Comment by hferentschik** [comment]
@Preeticp Will you change the commit message or shall I do it?

**Comment by Preeticp** [comment]
Done, as per your instructions in IRC. Checked with Git Log, it shows the changed message. Let me know  if it is not done right, I would like to do this myself, so that I can learn.

**Comment by hferentschik** [comment]
>  Checked with Git Log, it shows the changed message.

Good

> Let me know if it is not done right, I would like to do this myself, so that I can learn.

As far as I can tell, you have not pushed the changes to your feature branch. There is no updated commit in this pull request. You will have to _force_ push (on your feature branch):

git push -f <your-fork> HEAD

This should push your local changes to the feature branch to the pull request.

**Comment by Preeticp** [comment]
@hferentschik $ git push -f HEAD gave me the following error:
`fatal: 'HEAD' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.`
However I was able to do $ git push origin branch_name -f and I think it worked. Do let me know if there are any concerns.

**Comment by hferentschik** [comment]
Sorry, parts of my message disappeared in my last comment, since I forgot to escape properly

```
git push -f <fork> HEAD
```

HEAD is just a git "alias" for the current branch. By using head you don't have to think about the current branch name.

**Review by hferentschik — APPROVED** [review]
Looking good

**Comment by Preeticp** [comment]
Thanks @hferentschik, parts within angular brackets seem to disappear in the comments, you need to use  backticks for it to show I guess, like`<xyz>`.

**Pull request merged**
