### PR TITLE
Don't set private network for unsupported box

### LINKED ISSUE #232: Private network is being set for unsupported box
**Steps to Reproduce**:
- `vagrant init debian/jessie64`

Logs:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/jessie64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Setting the name of the VM: test_default_1463904952697_76908
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
-----------------------------------------------------------------------------------
==> default: When using virtualbox, a non-NAT network interface is required.
==> default: Adding a private network using DHCP
-----------------------------------------------------------------------------------
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
....
==> default: Machine booted and ready!
........
```

On uninstalling _vagrant-service-manager_, this issue get solved.

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #232

### CODE REVIEW

**Comment by hferentschik** [comment]
What's the issue key for that?

**Comment by brgnepal** [comment]
@hferentschik No issue key. This is what I found when I was solving this issue https://github.com/projectatomic/vagrant-service-manager/issues/220. 

I thought better fix it before any one file it.

**Comment by hferentschik** [comment]
> I thought better fix it before any one file it.

I think you should file it nevertheless and then link to it.

**Comment by navidshaikh** [comment]
LGTM.

**Pull request merged**
