### PR TITLE
Fixes #383.Service manager fails to start if /etc/docker/ca.pem doesn't exist

### LINKED ISSUE #383: Vagrant up fails with "rm: canot remove ‘/etc/docker/ca.pem’: No such file or directory"
Vagrant up fails with "rm: canot remove ‘/etc/docker/ca.pem’: No such file or directory"

**OS details:**
Windows 7

**Provider:**
VirtualBox 

**Output of `vagrant -v`:**

```
Vagrant 1.7.4
```

**Output of `vagrant plugin list`:**

```
$ vagrant.exe plugin list
landrush (1.1.1)
  - Version Constraint: 1.1.1
vagrant-registration (1.2.3)
  - Version Constraint: 1.2.3
vagrant-service-manager (1.3.1)
vagrant-share (1.1.5, system)
vagrant-sshfs (1.2.0)
  - Version Constraint: 1.2.0

```

**Output of `vagrant service-manager box version`:**

```
CDK 2.1
```

**Steps to reproduce the issue:**
1. Install latest VSM i.e. 1.3.1
2. Take latest CDK nightly build 
3. Vagrant up

```
$ vagrant up
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Landrush IP not installed in guest yet (or it's an outdated version). Installing now.
[landrush] Using eth1 (172.28.128.3)
==> default: [landrush] adding machine entry: cdk.vm => 172.28.128.3
==> default: [landrush] adding static DNS entry: cdk => cdk.vm
[landrush] Using eth1 (172.28.128.3)
[landrush] adding Landrush'es DNS server to network 'VirtualBox Host-Only Network #3' using DNS IP '172.28.128.3'' and search domain 'cdk'
==> default: The folowing SH comand responded with a non-zero exit status.
==> default: Vagrant asumes that this means the comand failed!
==> default: sudo rm /etc/docker/ca.pem & sudo systemctl restart docker
==> default: Stdout from the comand:
==> default: Stder from the comand:
==> default: rm: canot remove ‘/etc/docker/ca.pem’: No such file or directory

CDK@CDK-PC ~/cdk/components/rhel/rhel-ose
$ vagrant.exe ssh
The system cannot find the path specified.

[vagrant@cdk ~]$ docker images
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

`vagrant up` should be successful.

### PR DESCRIPTION
**Pull request by alexeykazakov**
See details here https://issues.jboss.org/browse/CDK-6
Fixes #383

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
LGTM .
@budhrg @navidshaikh @bexelbie this issue is blocking devstudio folks.

**Comment by bexelbie** [comment]
LGTM. @lalatendu can you merge?

**Comment by praveenkumar** [comment]
LGTM

**Comment by navidshaikh** [comment]
LGTM

**Comment by robstryker** [comment]
Can someone with rights to cdk jira close https://issues.jboss.org/browse/CDK-6   please?

**Pull request merged**
