### PR TITLE
Updated SPEC (v1.0.0) for url, date and format

### PR DESCRIPTION
**Pull request by brgnepal**
- Includes correction for date, repo url and other format changes

### CODE REVIEW

**Comment by brgnepal** [comment]
@navidshaikh @bexelbie Important PR for release `1.0.0`.

**Comment by navidshaikh** [comment]
LGTM. Thanks!

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by navidshaikh** [comment]
Here is the build link at copr: https://copr.fedorainfracloud.org/coprs/nshaikh/vagrant-service-manager/build/174010/

**Pull request merged**
