### PR TITLE
Fix #341: Update gemspec with development dependencies

### LINKED ISSUE #341: Update gemspec with development dependencies
Updating gemspec with development dependencies will reflect the changes in rubygem's gem page.
This will help to quickly know the dependencies through rubygems instead of going through github repo and check Gemfile or gemspec.

Refer this nice blog post on [`roles of Gemfile and .gemspec` 2nd para](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)

Example gem:
screenshot from 2016-07-15 13-48-20

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #341

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
-1 for release 1.2.1. Why are we even adding more things to 1.2.1. 1.2.1 is a release to fix the blocker which was caused by 1.2.0. What am I missing?

**Comment by hferentschik** [comment]
I am torn on this one, since we are not able to move all development dependencies. the Vagrant, vagrant-libvirt and fog-libvirt will always have to stay in the Gemfile. I find that unfortunate. Also, we will always have to keep the plugin group. 

What we can do though is to "merge" the test group into the development one.

I also agree with @LalatenduMohanty, this is a bug fix release. We should not change more code than necessary. I'd rather just fix the rubyzip thing. The other issues we added to 1.2.1 are just doc changes.

**Comment by brgnepal** [comment]
@LalatenduMohanty @hferentschik Ok we will add in next major version then.

**Comment by hferentschik** [comment]
> Ok we will add in next major version then.

-1 from my side. Why would you split up development dependencies in two places. That is confusing imo. Sure, if we could move all of them, it would make sense, but gemsepc does not allow for things like github references or the conditional inclusion of dependencies.

Also from a user perspective we would be displaying incomplete information. The most important dependency would be missing - Vagrant.

I fully agree it would be desirable to have all dependencies in gemspec, but given this is not possible, I'd opt for keeping them combined in one place.

**Comment by brgnepal** [comment]
Closing as we are not having consensus on adding dependencies in `.gemspec`

**Pull request closed without merging**
