### PR TITLE
Add "start" as an alias for "restart"

### PR DESCRIPTION
**Pull request by bexelbie**
This allows some instructions and concepts to "read" better.

Helps with https://github.com/projectatomic/adb-atomic-developer-bundle/pull/386

### CODE REVIEW

**Comment by bexelbie** [comment]
@budhrg

**Comment by LalatenduMohanty** [comment]
IMO restart and start are two different things, so we should not generalize both.

**Comment by bexelbie** [comment]
@LalatenduMohanty can you provide some guidance on how you see the code that implements them differing?  I didn't see any reason to modify the code.

**Comment by brgnepal** [comment]
@bexelbie , @LalatenduMohanty : With this PR https://github.com/projectatomic/vagrant-service-manager/pull/219 , we may not need this PR since setting alias is confusing and under the hood it is performing `restart` operation.

**Comment by bexelbie** [comment]
Closing to be replaced by #219

**Pull request closed without merging**
