### PR TITLE
Fix #446 Support folder as path in install-cli '--path' option

### LINKED ISSUE #446: Support path as folder path instead of path with binary name in install-cli --path option.
Currently, the 'install-cli' --path option need the mention of binary name like 'oc' or 'docker'.

Eg: --path /home/user/cli/oc   

for Openshift.

We should support path as folder instead of binary path.

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #446

### CODE REVIEW

**Review by hferentschik — COMMENTED** [review]
Changes look good to me. They passed the CI tests against CDK and ADB. Tests also passed on my machine.

Only thing I am wondering whether this is something we should do now, given that we want to make minimal changes for the user. 

I am wondering what others things. @LalatenduMohanty @praveenkumar !?

**Comment by praveenkumar** [comment]
> Only thing I am wondering whether this is something we should do now, given that we want to make minimal changes for the user.

I agree. This change is already tested out and passed CI so let's merge this and then we will not put any effort here.

**Review by praveenkumar — APPROVED** [review]

**Review by praveenkumar — APPROVED** [review]
LGTM

**Comment by LalatenduMohanty** [comment]
Agree with @hferentschik , this is not a blocker and not planned for CDK 2.4 release. However we can merge this and take this for 2.4 as this has passed review and testing.

**Comment by brgnepal** [comment]
> Agree with @hferentschik , this is not a blocker and not planned for CDK 2.4 release. However we can merge this and take this for 2.4 as this has passed review and testing.

:+1:

**Review by hferentschik — APPROVED** [review]
Ok, let's go ahead then ...

**Pull request merged**
