### PR TITLE
Fix #285: Native methods to detect host platform

### LINKED ISSUE #285: Use native methods to detect host platform instead of OS module
Hi,

Vagrant have dedicated class for detecting host platform which are defined in https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/platform.rb.

This class support extra methods other than detecting host platform.

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #285 

Tested on linux and windows.

### CODE REVIEW

**Comment by navidshaikh** [comment]
Cool! I will test it on Mac.

**Comment by hferentschik** [comment]
Nice. Looking into it asap.

**Comment by brgnepal** [comment]
retest this please

**Comment by hferentschik** [comment]
Personally I'd have nothing against making this part of the feature you are working currently on. This "pollutes" the changelog with internal refactorings which is not really interesting for users. But sure, this is a good change. Did the same thing a while ago on Landrush.

**Comment by hferentschik** [comment]
Rebased and merged :-)

**Pull request closed without merging**
