### PR TITLE
Fix #270: Fix DOCKER_API_VERSION properly on Windows

### LINKED ISSUE #270: DOCKER_API_VERSION not set properly on Windows
In em.yml:

```
        setx DOCKER_API_VERSION=#{api_version}
```

probably should be

```
        setx DOCKER_API_VERSION=%{api_version}
```

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #270

### CODE REVIEW

**Comment by brgnepal** [comment]
Do not merge. Checking how it got slipped off.

**Comment by brgnepal** [comment]
Tests are passing in Linux. Since, our main dev environment is Linux so far and hence this small typo error got slipped off.
We will make Windows as dev environment to ensure that such error don't get slip off.

**Comment by hferentschik** [comment]
retest this please

**Comment by hferentschik** [comment]
+1 Looking good.

**Comment by optak** [comment]
LGTM, it's just typo fix.
Just note: on windows, detection of terminal don't work correctly. Currently, it's based on variable VAGRANT_DETECTED_OS. If this variable equals "cygwin", than export is printed, setx otherwise.
More info in #10

**Comment by hferentschik** [comment]
rebased and merged, thanks

**Pull request closed without merging**
